#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SuiteSparse
Version  : 4.5.5
Release  : 3
URL      : http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.5.tar.gz
Source0  : http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 LGPL-2.1
Requires: SuiteSparse-lib
Requires: SuiteSparse-data
BuildRequires : cmake
BuildRequires : openblas
BuildRequires : tbb-dev
Patch1: build.patch
Patch2: ivdep.patch

%description
This file contains some test graphs and meshes
4elt.graph
copter2.graph
mdual.graph
These are small to medium size graphs corresponding to 2D and 3D
finite element mesh. They can be used as inputs to gpmetis and ndmetis.

%package data
Summary: data components for the SuiteSparse package.
Group: Data

%description data
data components for the SuiteSparse package.


%package dev
Summary: dev components for the SuiteSparse package.
Group: Development
Requires: SuiteSparse-lib
Requires: SuiteSparse-data
Provides: SuiteSparse-devel

%description dev
dev components for the SuiteSparse package.


%package lib
Summary: lib components for the SuiteSparse package.
Group: Libraries
Requires: SuiteSparse-data

%description lib
lib components for the SuiteSparse package.


%prep
%setup -q -n SuiteSparse
%patch1 -p1
%patch2 -p1
pushd ..
cp -a SuiteSparse buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505595422
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-common -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
make V=1  %{?_smp_mflags} BLAS=-lopenblas LAPACK=-lopenblas library metis

%install
export SOURCE_DATE_EPOCH=1505595422
rm -rf %{buildroot}
pushd ../buildavx2/
%make_install BLAS=-lopenblas LAPACK=-lopenblas INSTALL=%{buildroot}/usr  INSTALL_LIB=%{buildroot}/usr/lib64 || :
popd
%make_install BLAS=-lopenblas LAPACK=-lopenblas INSTALL=%{buildroot}/usr  INSTALL_LIB=%{buildroot}/usr/lib64 || :
## make_install_append content
cp -a include %{buildroot}/usr
## make_install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/doc/suitesparse-4.5.5/AMD_README.txt
/usr/share/doc/suitesparse-4.5.5/AMD_UserGuide.pdf
/usr/share/doc/suitesparse-4.5.5/BTF_README.txt
/usr/share/doc/suitesparse-4.5.5/CAMD_README.txt
/usr/share/doc/suitesparse-4.5.5/CAMD_UserGuide.pdf
/usr/share/doc/suitesparse-4.5.5/CCOLAMD_README.txt
/usr/share/doc/suitesparse-4.5.5/COLAMD_README.txt
/usr/share/doc/suitesparse-4.5.5/SUITESPARSECONFIG_README.txt

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/*.hpp
/usr/include/.gitignore
/usr/lib64/libamd.so
/usr/lib64/libbtf.so
/usr/lib64/libcamd.so
/usr/lib64/libccolamd.so
/usr/lib64/libcolamd.so
/usr/lib64/libsuitesparseconfig.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libamd.so.2
/usr/lib64/libamd.so.2.4.6
/usr/lib64/libbtf.so.1
/usr/lib64/libbtf.so.1.2.6
/usr/lib64/libcamd.so.2
/usr/lib64/libcamd.so.2.4.6
/usr/lib64/libccolamd.so.2
/usr/lib64/libccolamd.so.2.9.6
/usr/lib64/libcolamd.so.2
/usr/lib64/libcolamd.so.2.9.6
/usr/lib64/libsuitesparseconfig.so.4
/usr/lib64/libsuitesparseconfig.so.4.5.5
